name: diopi-impl ci
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

env:
  NFS_PATH: '/mnt/cache/share/parrotsci/github/cibuild/${{ github.repository }}'
  ENV_PATH: '/mnt/cache/share/platform/cienv'
  ENV_NAME: 'pt1.10v2'
  GPU_REQUESTS: 1
  SLURM_PAR_SH1984: ${{ secrets.SLURM_PAR_SH1984 }}
  CLUSTER_1984: SH1984

jobs:
  Rsync:
    name: Rsync code
    runs-on: github-diopi-ci
    steps:
      - name: clone repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.CI_TOKEN }}
          fetch-depth: '0'
          submodules: 'true'
      - name: Rsync to Server
        run: |
          ssh ${CLUSTER_1984} "mkdir -p ${NFS_PATH}/${GITHUB_RUN_NUMBER}/source"
          rsync -a --delete ${GITHUB_WORKSPACE}/ ${CLUSTER_1984}:${NFS_PATH}/${GITHUB_RUN_NUMBER}/source/

  lint-c-python:
    name: lint-python
    runs-on: github-diopi-ci
    needs: [Rsync]
    steps:
      - name: lint-c-python
        run: |
          ssh ${CLUSTER_1984} """
          set -e
          cd ${NFS_PATH}/ && ls -al && find ${NFS_PATH}/ -maxdepth 1 -ctime 1 -type d |xargs rm -rf
          source ${ENV_PATH}/github_bashrc && source /mnt/cache/share/platform/env/${ENV_NAME}
          cd ${NFS_PATH}/${GITHUB_RUN_NUMBER} && rm -rf ${GITHUB_JOB} && cp -R source ${GITHUB_JOB} && cd ${GITHUB_JOB}
          export CI=true
          srun --job-name=${GITHUB_JOB} --partition=${SLURM_PAR_SH1984} --time=40 bash scripts/ci_script.sh cpp-lint
          """